// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triumph.Web.Data;

namespace Triumph.Web.Migrations
{
    [DbContext(typeof(TriumphDbContext))]
    [Migration("20181219175137_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Triumph.Web.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedEmpID");

                    b.Property<string>("BusinessName");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Notes");

                    b.Property<string>("Phone");

                    b.HasKey("ClientID");

                    b.HasIndex("AssignedEmpID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Notes");

                    b.Property<string>("Phone");

                    b.HasKey("EmpID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedClientIDClientID");

                    b.Property<int?>("AssignedEmpIDEmpID");

                    b.Property<string>("Attributes");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("Name");

                    b.Property<string>("Priority");

                    b.HasKey("ID");

                    b.HasIndex("AssignedClientIDClientID");

                    b.HasIndex("AssignedEmpIDEmpID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Client", b =>
                {
                    b.HasOne("Triumph.Web.Entities.Employee", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedEmpID");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Project", b =>
                {
                    b.HasOne("Triumph.Web.Entities.Client", "AssignedClientID")
                        .WithMany()
                        .HasForeignKey("AssignedClientIDClientID");

                    b.HasOne("Triumph.Web.Entities.Employee", "AssignedEmpID")
                        .WithMany()
                        .HasForeignKey("AssignedEmpIDEmpID");
                });
#pragma warning restore 612, 618
        }
    }
}
